# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170928_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='developer',
        ),
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.ManyToManyField(to='courses.Developer'),
        ),
    ]
