# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170928_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='developer',
            new_name='developers',
        ),
    ]
